"""empty message

Revision ID: 9403c9872083
Revises: 9a3742bfd1b9
Create Date: 2022-06-08 18:52:12.816171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9403c9872083'
down_revision = '9a3742bfd1b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
